name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: for OUTPUT in $(find . -name "Dockerfile"); do IMAGE_TAG=$(echo docker.pkg.github.com/tsickert/$(cut -d/ -f2 <<< "$OUTPUT"):$(date +%s)) && docker build -t $IMAGE_TAG -f $OUTPUT . && docker login https://docker.pkg.github.com -u tsickert -p ${{ secrets.GITHUB_TOKEN }} && docker push $IMAGE_TAG; done;
